version: '3'

services:
  redis:
    image: "redis:alpine"

  app:
    build: .
    container_name: app
    command: daphne -b 0.0.0.0 -p 8000 jobseeker.asgi:application
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis

  database:
    image: postgres
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - "54320:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data

  celery:
    build: .
    container_name: celery
    command: celery --app=jobseeker worker -l INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

volumes:
  pgdbdata: