# Generated by Django 5.0.4 on 2024-05-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='responses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
