# Generated by Django 5.0.4 on 2024-05-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vacancy_responses_vacancy_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='responses',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='views',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responses',
            field=models.ManyToManyField(related_name='responded_vacancies', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='views',
            field=models.ManyToManyField(related_name='viewed_vacancies', to='main.userprofile'),
        ),
    ]
