# Generated by Django 5.0.4 on 2024-05-02 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
    ]
