# Generated by Django 5.0.4 on 2024-05-02 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_hr_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.hr'),
        ),
    ]
