# Generated by Django 5.0.4 on 2024-07-12 12:29

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_hr_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='contact_info',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='first_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='last_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_info',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expected_salary_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='pfp/'),
        ),
    ]
